<?php

namespace MMSEBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ControlusuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlusuariosRepository extends EntityRepository
{
}
